/* Menrva - Over-Engineered Tunable Android Audio Effects
 * Copyright (C) 2020 Justin Giannone (aka Jman420)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

/* --------------------------DO NOT EDIT THIS FILE--------------------------
 * This file has been generated by the generate_command_handler_map.ps1 script.
 * To regenerate this file re-execute generate_command_handler_map.ps1
 *
 * Template File : menrva/app/src/main/templates/CommandHandlerMap.h.template 
 */

#ifndef MENRVA_COMMAND_HANDLER_MAP_H
#define MENRVA_COMMAND_HANDLER_MAP_H

#include <map>
#include "../command_handlers/CommandHandlerBase.h"

typedef std::map<uint32_t, CommandHandlerBase*> handler_map;

class CommandHandlerMap {
public:
    CommandHandlerMap(LogWriterBase* logger);

    handler_map* GetMap();
    CommandHandlerBase* GetCommandHandler(uint32_t commandId);

private:
    handler_map* _HandlerMap;

    void Initialize(LogWriterBase* logger);
};

#endif //MENRVA_COMMAND_HANDLER_MAP_H
