/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_monkeystable_menrva_activities_JniInterface */

#ifndef _Included_com_monkeystable_menrva_activities_JniInterface
#define _Included_com_monkeystable_menrva_activities_JniInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_monkeystable_menrva_activities_JniInterface
 * Method:    getMenrvaEffectTypeUUID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_monkeystable_menrva_activities_JniInterface_getMenrvaEffectTypeUUID
  (JNIEnv* env, jclass caller);

/*
 * Class:     com_monkeystable_menrva_activities_JniInterface
 * Method:    getMenrvaEffectEngineUUID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_monkeystable_menrva_activities_JniInterface_getMenrvaEffectEngineUUID
  (JNIEnv* env, jclass caller);

#ifdef __cplusplus
}
#endif
#endif
