/* Menrva - Over-Engineered Tunable Android Audio Effects
 * Copyright (C) 2020 Justin Giannone (aka Jman420)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

/* --------------------------DO NOT EDIT THIS FILE--------------------------
 * This file has been generated by the generate_command_handler_map.ps1 script.
 * To regenerate this file re-execute generate_command_handler_map.ps1
 *
 * Template File : menrva/app/src/main/templates/CommandHandlerMap.cpp.template 
 */

#include "CommandHandlerMap.h"
#include "../commands/MenrvaCommands.h"

CommandHandlerMap::CommandHandlerMap(LogWriterBase* logger) {
    _HandlerMap = new handler_map();
    Initialize(logger);
}

handler_map* CommandHandlerMap::GetMap() {
    return _HandlerMap;
}

CommandHandlerBase* CommandHandlerMap::GetCommandHandler(uint32_t commandId) {
    handler_map& handlerMap = *_HandlerMap;

    auto cmdFunction = handlerMap.find(commandId);
    if (cmdFunction == handlerMap.end()) {
        return nullptr;
    }

    return cmdFunction->second;
}


#include "../command_handlers/Engine_GetLogLevel_Handler.h"
#include "../command_handlers/Engine_GetVersion_Handler.h"
#include "../command_handlers/Engine_SetLogLevel_Handler.h"

void CommandHandlerMap::Initialize(LogWriterBase* logger) {
    handler_map& handlerMap = *_HandlerMap;
    CommandHandlerBase* commandHandler = nullptr;

    commandHandler = new Engine_GetLogLevel_Handler(logger); handlerMap.insert(handler_map::value_type(commandHandler->GetCommand()->GetCommandId(), commandHandler));
    commandHandler = new Engine_GetVersion_Handler(logger); handlerMap.insert(handler_map::value_type(commandHandler->GetCommand()->GetCommandId(), commandHandler));
    commandHandler = new Engine_SetLogLevel_Handler(logger); handlerMap.insert(handler_map::value_type(commandHandler->GetCommand()->GetCommandId(), commandHandler));
}
