// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Engine_GetLogLevel.proto

package com.monkeystable.menrva.commands.messages;

public final class Engine_GetLogLevel {
  private Engine_GetLogLevel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface Engine_GetLogLevel_RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.Engine_GetLogLevel_Request)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code messages.Engine_GetLogLevel_Request}
   */
  public  static final class Engine_GetLogLevel_Request extends
      com.google.protobuf.GeneratedMessageLite<
          Engine_GetLogLevel_Request, Engine_GetLogLevel_Request.Builder> implements
      // @@protoc_insertion_point(message_implements:messages.Engine_GetLogLevel_Request)
      Engine_GetLogLevel_RequestOrBuilder {
    private Engine_GetLogLevel_Request() {
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code messages.Engine_GetLogLevel_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request, Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.Engine_GetLogLevel_Request)
        com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_RequestOrBuilder {
      // Construct using com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:messages.Engine_GetLogLevel_Request)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = null;java.lang.String info =
                "\u0000\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request> parser = PARSER;
          if (parser == null) {
            synchronized (com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:messages.Engine_GetLogLevel_Request)
    private static final com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new Engine_GetLogLevel_Request();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Engine_GetLogLevel_Request.class, DEFAULT_INSTANCE);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Engine_GetLogLevel_Request> PARSER;

    public static com.google.protobuf.Parser<Engine_GetLogLevel_Request> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface Engine_GetLogLevel_ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.Engine_GetLogLevel_Response)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 LogLevel = 1;</code>
     */
    int getLogLevel();
  }
  /**
   * Protobuf type {@code messages.Engine_GetLogLevel_Response}
   */
  public  static final class Engine_GetLogLevel_Response extends
      com.google.protobuf.GeneratedMessageLite<
          Engine_GetLogLevel_Response, Engine_GetLogLevel_Response.Builder> implements
      // @@protoc_insertion_point(message_implements:messages.Engine_GetLogLevel_Response)
      Engine_GetLogLevel_ResponseOrBuilder {
    private Engine_GetLogLevel_Response() {
    }
    public static final int LOGLEVEL_FIELD_NUMBER = 1;
    private int logLevel_;
    /**
     * <code>int32 LogLevel = 1;</code>
     */
    @java.lang.Override
    public int getLogLevel() {
      return logLevel_;
    }
    /**
     * <code>int32 LogLevel = 1;</code>
     */
    private void setLogLevel(int value) {
      
      logLevel_ = value;
    }
    /**
     * <code>int32 LogLevel = 1;</code>
     */
    private void clearLogLevel() {
      
      logLevel_ = 0;
    }

    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code messages.Engine_GetLogLevel_Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response, Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.Engine_GetLogLevel_Response)
        com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_ResponseOrBuilder {
      // Construct using com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 LogLevel = 1;</code>
       */
      @java.lang.Override
      public int getLogLevel() {
        return instance.getLogLevel();
      }
      /**
       * <code>int32 LogLevel = 1;</code>
       */
      public Builder setLogLevel(int value) {
        copyOnWrite();
        instance.setLogLevel(value);
        return this;
      }
      /**
       * <code>int32 LogLevel = 1;</code>
       */
      public Builder clearLogLevel() {
        copyOnWrite();
        instance.clearLogLevel();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messages.Engine_GetLogLevel_Response)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "logLevel_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response> parser = PARSER;
          if (parser == null) {
            synchronized (com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:messages.Engine_GetLogLevel_Response)
    private static final com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new Engine_GetLogLevel_Response();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Engine_GetLogLevel_Response.class, DEFAULT_INSTANCE);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetLogLevel.Engine_GetLogLevel_Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Engine_GetLogLevel_Response> PARSER;

    public static com.google.protobuf.Parser<Engine_GetLogLevel_Response> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
