// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Engine_GetVersion.proto

package com.monkeystable.menrva.commands.messages;

public final class Engine_GetVersion {
  private Engine_GetVersion() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface Engine_GetVersion_RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.Engine_GetVersion_Request)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code messages.Engine_GetVersion_Request}
   */
  public  static final class Engine_GetVersion_Request extends
      com.google.protobuf.GeneratedMessageLite<
          Engine_GetVersion_Request, Engine_GetVersion_Request.Builder> implements
      // @@protoc_insertion_point(message_implements:messages.Engine_GetVersion_Request)
      Engine_GetVersion_RequestOrBuilder {
    private Engine_GetVersion_Request() {
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code messages.Engine_GetVersion_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request, Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.Engine_GetVersion_Request)
        com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_RequestOrBuilder {
      // Construct using com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:messages.Engine_GetVersion_Request)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = null;java.lang.String info =
                "\u0000\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request> parser = PARSER;
          if (parser == null) {
            synchronized (com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:messages.Engine_GetVersion_Request)
    private static final com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new Engine_GetVersion_Request();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Engine_GetVersion_Request.class, DEFAULT_INSTANCE);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Engine_GetVersion_Request> PARSER;

    public static com.google.protobuf.Parser<Engine_GetVersion_Request> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface Engine_GetVersion_ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.Engine_GetVersion_Response)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 major = 1;</code>
     */
    int getMajor();

    /**
     * <code>int32 minor = 2;</code>
     */
    int getMinor();

    /**
     * <code>int32 patch = 3;</code>
     */
    int getPatch();
  }
  /**
   * Protobuf type {@code messages.Engine_GetVersion_Response}
   */
  public  static final class Engine_GetVersion_Response extends
      com.google.protobuf.GeneratedMessageLite<
          Engine_GetVersion_Response, Engine_GetVersion_Response.Builder> implements
      // @@protoc_insertion_point(message_implements:messages.Engine_GetVersion_Response)
      Engine_GetVersion_ResponseOrBuilder {
    private Engine_GetVersion_Response() {
    }
    public static final int MAJOR_FIELD_NUMBER = 1;
    private int major_;
    /**
     * <code>int32 major = 1;</code>
     */
    @java.lang.Override
    public int getMajor() {
      return major_;
    }
    /**
     * <code>int32 major = 1;</code>
     */
    private void setMajor(int value) {
      
      major_ = value;
    }
    /**
     * <code>int32 major = 1;</code>
     */
    private void clearMajor() {
      
      major_ = 0;
    }

    public static final int MINOR_FIELD_NUMBER = 2;
    private int minor_;
    /**
     * <code>int32 minor = 2;</code>
     */
    @java.lang.Override
    public int getMinor() {
      return minor_;
    }
    /**
     * <code>int32 minor = 2;</code>
     */
    private void setMinor(int value) {
      
      minor_ = value;
    }
    /**
     * <code>int32 minor = 2;</code>
     */
    private void clearMinor() {
      
      minor_ = 0;
    }

    public static final int PATCH_FIELD_NUMBER = 3;
    private int patch_;
    /**
     * <code>int32 patch = 3;</code>
     */
    @java.lang.Override
    public int getPatch() {
      return patch_;
    }
    /**
     * <code>int32 patch = 3;</code>
     */
    private void setPatch(int value) {
      
      patch_ = value;
    }
    /**
     * <code>int32 patch = 3;</code>
     */
    private void clearPatch() {
      
      patch_ = 0;
    }

    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code messages.Engine_GetVersion_Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response, Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.Engine_GetVersion_Response)
        com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_ResponseOrBuilder {
      // Construct using com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 major = 1;</code>
       */
      @java.lang.Override
      public int getMajor() {
        return instance.getMajor();
      }
      /**
       * <code>int32 major = 1;</code>
       */
      public Builder setMajor(int value) {
        copyOnWrite();
        instance.setMajor(value);
        return this;
      }
      /**
       * <code>int32 major = 1;</code>
       */
      public Builder clearMajor() {
        copyOnWrite();
        instance.clearMajor();
        return this;
      }

      /**
       * <code>int32 minor = 2;</code>
       */
      @java.lang.Override
      public int getMinor() {
        return instance.getMinor();
      }
      /**
       * <code>int32 minor = 2;</code>
       */
      public Builder setMinor(int value) {
        copyOnWrite();
        instance.setMinor(value);
        return this;
      }
      /**
       * <code>int32 minor = 2;</code>
       */
      public Builder clearMinor() {
        copyOnWrite();
        instance.clearMinor();
        return this;
      }

      /**
       * <code>int32 patch = 3;</code>
       */
      @java.lang.Override
      public int getPatch() {
        return instance.getPatch();
      }
      /**
       * <code>int32 patch = 3;</code>
       */
      public Builder setPatch(int value) {
        copyOnWrite();
        instance.setPatch(value);
        return this;
      }
      /**
       * <code>int32 patch = 3;</code>
       */
      public Builder clearPatch() {
        copyOnWrite();
        instance.clearPatch();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messages.Engine_GetVersion_Response)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "major_",
              "minor_",
              "patch_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0004\u0002\u0004" +
                "\u0003\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response> parser = PARSER;
          if (parser == null) {
            synchronized (com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:messages.Engine_GetVersion_Response)
    private static final com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new Engine_GetVersion_Response();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Engine_GetVersion_Response.class, DEFAULT_INSTANCE);
    }
    public static com.monkeystable.menrva.commands.messages.Engine_GetVersion.Engine_GetVersion_Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Engine_GetVersion_Response> PARSER;

    public static com.google.protobuf.Parser<Engine_GetVersion_Response> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
